import type { Metadata } from "next";
import "./globals.css";
import TanstackQueryProvider from "./lib/contexts/TanstackQueryProvider";
import { AuthenticationPage } from "./components/AuthenticationPage";
import { ThemeProvider } from "./components/ThemeProvider/ThemeProvider";
import { Navbar } from "./components/Navbar";
import { Toaster } from "./components/ui/toaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased flex flex-row">
        <TanstackQueryProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <AuthenticationPage />

            {/* {session && <Navbar>{children}</Navbar>} */}
            <Toaster />
          </ThemeProvider>
        </TanstackQueryProvider>
      </body>
    </html>
  );
}
