import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import SessionProvider from "./lib/contexts/SessionProvider";
import TanstackQueryProvider from "./lib/contexts/TanstackQueryProvider";
import { AuthenticationPage } from "./components/AuthenticationPage";
import { ThemeProvider } from "./components/ThemeProvider/ThemeProvider";
import { Navbar } from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased flex flex-row`}>
        <TanstackQueryProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <SessionProvider session={session}>
              {!session && <AuthenticationPage />}

              {session && <Navbar>{children}</Navbar>}
            </SessionProvider>
          </ThemeProvider>
        </TanstackQueryProvider>
      </body>
    </html>
  );
}
